[package]
name = "zksync-era-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zksync-web3-rs = { git = "https://www.github.com/LambdaClass/zksync-web3-rs", rev="54c2145cee69bbc5e2f55c6bdfc5662ef250cd0c", features = ["ethers-solc"]}
tokio = "1"
env_logger = "0.10"
log = "0.4"
clap = "4.3"
eyre = "0.6"
serde_json = "1"
serde = "1"
thiserror = "1"
hex = "0.4"
