name: Publish to crates.io

on:
  push:
    tags: # Pattern matched against refs/tags
      - '*' # Push events to every tag not containing /

jobs:

  run_qa_checks:
    name: "Run automated QA checks"
    uses: ./.github/workflows/quality.yaml

  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    needs: run_qa_checks # Never run if automated QA checks aren't met
    steps:

      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Rustup toolchain install
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: "Publish to crates.io"
        run: cargo publish --dry-run
        # run: cargo publish --token ${CRATES_IO_TOKEN}
        # env:
        #   CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
